learning_users/base_app/urls.py
from django.urls import path
from base_app import views

# Template URLS!
app_name = 'base_app'

urlpatterns = [
    path('register/', views.registerView, name="register"),
    path('user_login/', views.user_loginView, name="user_login"),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from base_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.indexView, name="index"),
    path('base_app/', include('base_app.urls')),
    path('logout/', views.user_logoutView, name='logout'),
    path('special',views.specialView, name='special'),
    path('login/', views.user_loginView, name='login')
]

learning_users/base_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
	# Create relationship (dont inherit from user!)
	user = models.OneToOneField(User, on_delete=True)
	# add any additional attributes you want
	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    # v adresari "media" si vytvorime novy subfolder "profile_pics"
	def __str__(self):
		# built-in attribute of django.contrib.auth.models.User
		return self.user.username

learning_users/base_app/forms.py
from django import forms
from django.contrib.auth.models import User
from base_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/base_app/views.py
from django.shortcuts import render
from base_app.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
# ak chceme aby user musel byt prihlaseni tak pouzijeme:
from django.contrib.auth.decorators import login_required
# Create your views here.

def indexView(request):
    return render(request, 'base_app/index.html')

@login_required
def specialView(request):
    return HttpResponse('You are logged in, Nice!')

@login_required
def user_logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('index')) # index view

def registerView(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']\

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'base_app/registration.html',
                            {'user_form': user_form,
                            'profile_form': profile_form,
                            'registered':registered})

def user_loginView(request):

    if request.method == 'POST':
        username = request.POST.get('username') # v login.html je to username
        password = request.POST.get('password') # v login.html je to password

        user = authenticate(username=username, password=password) # true/false

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index')) # index view
            else:
                return HttpResponse('Account is not active')
        else:
            print('Someone tried to login and failed!')
            print('Username: {} and password: {}'.format(username,password))
    else:
        return render(request, 'base_app/login.html',{})

learning_users/templates/base_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Bootstrap link -->
    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Django</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'base_app:register' %}">Register</a></li>
          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
            <!-- "logout" je prepojeny na urls.py subor, kde je nazov 'logout' -->
          {% else %}
            <li><a class="navbar-link" href="{% url 'base_app:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

learning_users/templates/base_app/index.html
{% extends "base_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django level five home page</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

{% endblock %}

learning_users/templates/base_app/login.html
{% extends "base_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please login</h1>
  <form action="{% url 'base_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Enter Password">
    <input type="submit" name="" value="Login">
  </form>
</div>

{% endblock %}

learning_users/templates/base_app/registration.html
{% extends "base_app/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registration!</h1>
  {% else %}
    <h1>Register here!</h1>
    <h3>Fill out the form please!</h3>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>

  {% endif %}
</div>

{% endblock %}